### ISSUE TITLE
Add items, checkout in one click

### ISSUE THREAD

**Issue by BernardLerring** [BernardLerring/First-Agile-Project#1]
As a user **I can** add multiple items to my shopping basket so I **can** check out in one click

**Comment by BernardLerring** [comment]
In order to **receive benefit** as a **role**, I can **goal/desire**

### Acceptance Criteria

- Customer can add multiple items to shopping basket
- Checkout can be completed in one click
- Customer can save card details for speed of transaction

### Tasks

- [ ] Design shopping basket logo
- [ ] Write HTML and CSS for checkout page
- [ ] Write code for saving of card details
